### ISSUE TITLE
Add `path` or `lensePath` to JsonPath

### ISSUE THREAD

**Issue by VladPodilnyk** [circe/circe-optics#160]
__The problem__:
Given the following json:
```
{
  "data:0": [0, 122, [0, [111]]]
}
```
I wanna get a number `111` which in scala code looks like this
```scala
val lens = root.selectDynamic("data:0")(2)(1)(0).int
```
It would be useful have some method (e.g. `path`) which takes path (HList or list of strings) and return an element on given path. JS library Rambda already had them
https://ramdajs.com/docs/#path
https://ramdajs.com/docs/#lensPath

So this is rather a question or discussion about whether those functions should be added  or not?
Maybe there is an idiomatic Scala solution I don't know about?
/cc: @julien-truffaut @travisbrown

**Comment by travisbrown** [comment]
FWIW the [latest Circe milestone](https://github.com/circe/circe/releases/tag/v0.14.0-M3) includes a new JSON Pointer implementation:

```scala
scala> import io.circe.literal._, io.circe.pointer.literal._
import io.circe.literal._
import io.circe.pointer.literal._

scala> pointer"/data:0/2/1/0".get(json"""{"data:0": [0, 122, [0, [111]]]}""")
val res0: Either[io.circe.pointer.PointerFailure,io.circe.Json] = Right(111)
```

**Comment by VladPodilnyk** [comment]
Hmm, nice alternative. Thanks @travisbrown for suggestion. I think I might give it a try.
Do you think that JSON pointers make circe-optics obsolete? Seems like they are solving the same problem.

**Comment by travisbrown** [comment]
@VladPodilnyk There's definitely overlap in use cases, but circe-optics is more composable, fits in nicely in situations where you're already using Monocle, provides some convenient extractors, etc.

Personally I've typically chosen cursor manipulation over optics, anyway, and I'm more likely to choose either that or JSON pointers most of the time, but I don't think circe-optics is obsolete by any means.

**Comment by VladPodilnyk** [comment]
Thanks for answers!!!
I guess, this could be closed in case you won't plan to add those methods into `circe-optics`, since JSON pointers covers that case I've listed above.

**Comment by travisbrown** [comment]
Personally I have no objection to adding methods like that here, I just don't really have time to do it myself.

**Comment by VladPodilnyk** [comment]
I am kinda busy a little too, but I would like to add them. So in case there is no rush, I could tackle this when I'll have more free time. Is it OK?

**Comment by travisbrown** [comment]
@VladPodilnyk Yes, of course. Feel free to leave this issue open and ping me for review when you're ready.

**Comment by VladPodilnyk** [comment]
@travisbrown thanks!
