### ISSUE TITLE
Release 0.11.1 to bring the version in line with main Circe library

### ISSUE THREAD

**Issue by koterpillar** [circe/circe-optics#24]
I currently have the following in my Gradle build file:

```
circeVersion = '0.11.1'

// ...

compile "io.circe:circe-core_%%:${circeVersion}"
compile "io.circe:circe-generic_%%:${circeVersion}"
compile "io.circe:circe-parser_%%:${circeVersion}"
compile "io.circe:circe-optics_%%:0.11.0"
```

because 0.11.1 is not released to Maven.

It would be nice if the version of the optics was always in line with the main Circe library.

Alternatively, if that's not feasible, a note about optics version being different should be provided in the [optics documentation](https://circe.github.io/circe/optics.html) which currently simply says `circeVersion`.

**Comment by travisbrown** [comment]
@koterpillar We don't guarantee that the current version of all circe modules share the same patch number. Suppose for example that we need to publish a bug fix for circe-optics—it wouldn't be reasonable to republish every other module just to keep the version numbers in sync.

I'd happily accept a pull request changing the documentation as you suggest, thanks!
