### ISSUE TITLE
[Question] update and release schedule?

### ISSUE THREAD

**Issue by GreyPlane** [circe/circe-optics#302]
This project has been unmaintained for a long time, especially since one of the crucial dependencies Monocle has been outdated, and its API changes rapidly in the new versions.
If needed, I'm willing to do the necessary work to keep the dependency up to date.

**Comment by zmccoy** [comment]
Hi @GreyPlane I'd be happy to have you help out.  Please feel free to review and and submit the PRs tagging us.

**Comment by zmccoy** [comment]
@GreyPlane If you can get this https://github.com/circe/circe-optics/pull/305 over the line that would be great as that gets the builds and releases to work with ease rather than being unique per repo.

**Comment by GreyPlane** [comment]
Thanks, I will looking for it.

**Comment by GreyPlane** [comment]
@zmccoy #329 
it looks like all CI check passed.

**Comment by zmccoy** [comment]
@GreyPlane Got that merged, thanks a ton for that, sorry it took us a bit to get to.

**Comment by zmccoy** [comment]
@GreyPlane We'll get that merged, thanks a ton for that, sorry it took us a bit to get to.  Happy to merge any more things, please feel free to comment or approve PRs for the deps as well.  That would be fantastic.
